#Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#SPDX-License-Identifier: BSD-3-Clause-Clear

# --> telaf
simulation_env/telaf=https://git.codelinaro.org/clo/le/platform/TelAF.git telaf.lnx.1.1

# --> legato-af
simulation_env/legato/legato-af=https://git.codelinaro.org/clo/le/legato-af.git telaf.lnx.1.1

# --> kconfiglib
simulation_env/legato/3rdParty/Kconfiglib=https://git.codelinaro.org/clo/le/legatoproject/Kconfiglib.git caf_migration/refs/tags/20.04.0

# --> jansson
simulation_env/legato/3rdParty/jansson=https://git.codelinaro.org/clo/le/legatoproject/legato-3rdParty-jansson.git caf_migration/refs/tags/20.04.0

# --> sdk
simulation_env/sdk=https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/snaptel-sdk.git telsdk.lnx.2.0.r11-rel

# --> telaf-pa
simulation_env/telaf-pa=https://git.codelinaro.org/clo/le/platform/telaf-pa.git telaf-pa.lnx.1.0

# --> telaf-pa-default
simulation_env/telaf-pa-default=https://git.codelinaro.org/clo/le/platform/telaf-pa-default.git telaf.lnx.1.1
