cmake_minimum_required(VERSION 3.16)
project(taf_pa_common_stub LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(LIBRARY_VERSION "1.0.0")
set(LIBRARY_SOVERSION "1")
set(PROP_TARGET_NAME taf_prop_common)
set(PROP_OUTPUT_NAME Component_${PROP_TARGET_NAME})
set(NS_TARGET_NAME taf_ns_common)
set(NS_OUTPUT_NAME Component_${NS_TARGET_NAME})

add_library(${PROP_TARGET_NAME} SHARED taf_prop_common.cpp)
add_library(${NS_TARGET_NAME} SHARED taf_ns_common.cpp)

set_target_properties(${PROP_TARGET_NAME} PROPERTIES
    VERSION ${LIBRARY_VERSION}
    SOVERSION ${LIBRARY_SOVERSION}
    OUTPUT_NAME ${PROP_OUTPUT_NAME}
)
set_target_properties(${NS_TARGET_NAME} PROPERTIES
    VERSION ${LIBRARY_VERSION}
    SOVERSION ${LIBRARY_SOVERSION}
    OUTPUT_NAME ${NS_OUTPUT_NAME}
)

target_include_directories(${PROP_TARGET_NAME} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_include_directories(${NS_TARGET_NAME} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)

install(TARGETS ${PROP_TARGET_NAME}
    LIBRARY DESTINATION lib
)
install(TARGETS ${NS_TARGET_NAME}
    LIBRARY DESTINATION lib
)

