# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

services:

  telaf_simulation_develop_2204:
    build:
      context: .
      dockerfile: Dockerfile.2204.develop
      args:
        - DEVELOPER_UID=$DEVELOPER_UID
        - DEVELOPER_GID=$DEVELOPER_GID
        - UBUNTU_DISTRO_ORIGIN=$UBUNTU_DISTRO_ORIGIN
    image: telaf_simulation_develop_2204:1.0.0

  telaf_simulation_runtime_2204:
    build:
      context: .
      dockerfile: Dockerfile.2204.runtime
      args:
        - UBUNTU_DISTRO_ORIGIN=$UBUNTU_DISTRO_ORIGIN
    image: telaf_simulation_runtime_2204:1.0.0
