/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

#include "legato.h"
#include "interfaces.h"

le_result_t testDeviceConsole(char* dev)
{
    FILE *test_fp = fopen(dev, "w");
    if (test_fp == NULL)
    {
        LE_ERROR("Failed to open %s, %m", dev);
        return LE_FAULT;
    }

    // In some situations, the logs below may not be visible. However, if
    // no errors occur, we consider the write operation successful.
    if (fprintf(test_fp, "This output will be displayed on the console.\n") < 0)
    {
        LE_ERROR("Failed to write to %s, %m", dev);
        fclose(test_fp);
        return LE_FAULT;
    }
    fclose(test_fp);
    return LE_OK;
}

le_result_t testDeviceNull(char* dev)
{
    FILE *test_fp = fopen(dev, "w");
    if (test_fp == NULL)
    {
        LE_ERROR("Failed to open %s, %m", dev);
        return LE_FAULT;
    }
    if (fprintf(test_fp, "This output will be discarded.\n") < 0)
    {
        LE_ERROR("Failed to write to %s, %m", dev);
        fclose(test_fp);
        return LE_FAULT;
    }
    fclose(test_fp);
    return LE_OK;
}

le_result_t testDeviceZero(char* dev)
{
    int zero_fd = open(dev, O_RDONLY);
    if (zero_fd == -1)
    {
        LE_ERROR("Failed to open %s, %m", dev);
        return LE_FAULT;
    }

    char zero_buffer[16];
    ssize_t zero_read = read(zero_fd, zero_buffer, sizeof(zero_buffer));
    close(zero_fd);

    if (zero_read == -1)
    {
        LE_ERROR("Failed to read %s, %m", dev);
        return LE_FAULT;
    }
    if (zero_read < sizeof(zero_buffer))
    {
        LE_ERROR("Partial read from %s, %m", dev);
        return LE_FAULT;
    }
    // Print the buffer to verify it's filled with zero bytes
    LE_INFO("Buffer initialized with zero bytes:\n");
    for (int i = 0; i < 16; i++)
    {
        if (zero_buffer[i] != 0)
        {
            LE_ERROR("zero_buffer[%d] is not zero, %d", i, zero_buffer[i]);
            return LE_FAULT;
        }
        LE_INFO("%d ", zero_buffer[i]);
    }
    return LE_OK;
}

le_result_t testDeviceRandom(char* dev)
{
    unsigned char random_buffer[16] = {0};
    unsigned char zero_buffer[16] = {0};

    int urandom_fd = open(dev, O_RDONLY);
    if (urandom_fd == -1)
    {
        LE_ERROR("Failed to open %s, %m", dev);
        return LE_FAULT;
    }
    ssize_t urandom_read = read(urandom_fd, random_buffer, sizeof(random_buffer));
    close(urandom_fd);
    if (urandom_read == -1)
    {
        LE_ERROR("Failed to read %s, %m", dev);
        return LE_FAULT;
    }

    LE_INFO("Random bytes generated by %s:", dev);
    for (int i = 0; i < sizeof(random_buffer); i++)
    {
        LE_INFO("%02x ", random_buffer[i]);
    }

    if (memcmp(zero_buffer, random_buffer, 16) == 0)
    {
        LE_ERROR("Buffer is all zero");
        return LE_FAULT;
    }

    return LE_OK;
}

le_result_t testDeviceLog(char* dev)
{
    int fd = open(dev, O_WRONLY);
    if (fd == -1)
    {
        LE_ERROR("Failed to open %s, %m", dev);
        return LE_FAULT;
    }

    char test_message[128] = {0};
    snprintf(test_message, sizeof(test_message), "Test message to %s", dev);
    ssize_t bytes_written = write(fd, test_message, strlen(test_message));
    close(fd);

    if (bytes_written == -1)
    {
        LE_ERROR("Failed to write %s, %m", dev);
        return LE_FAULT;
    }

    return LE_OK;
}

void Test_devices(void)
{
    LE_TEST_ASSERT((testDeviceConsole("/dev/console") == LE_OK),
        "Test device: /dev/console");

    LE_TEST_ASSERT((testDeviceNull("/dev/null") == LE_OK),
        "Test device: /dev/null");

    LE_TEST_ASSERT((testDeviceZero("/dev/zero") == LE_OK),
        "Test device: /dev/zero");

    LE_TEST_ASSERT((testDeviceRandom("/dev/urandom") == LE_OK),
        "Test device: /dev/urandom");
    LE_TEST_ASSERT((testDeviceRandom("/dev/urandom2") == LE_OK),
        "Test device: /dev/urandom2");
}

COMPONENT_INIT
{
    LE_INFO("------- Started testing links in sandbox -------");

    Test_devices();

    LE_INFO("---------- All Tests Completed ----------------");

    LE_TEST_EXIT;
}
